export const text = {
    bold :'Poppins-Bold',
    semiBold : 'Poppins-SemiBold',
    thin : 'Poppins-Thin',
    regular : 'Poppins-Regular',
    light : 'Poppins-Light',
    extraLight : 'Poppins-ExtraLight',
    medium : 'Poppins-Medium',
    thinItalic : 'Poppins-ThinItalic',
    extraLightItalic : 'Poppins-ExtraLightItalic',
    lightItalic : 'Poppins-LightItalic',
    italic : 'Poppins-Italic',
    mediumItalic : 'Poppins-MediumItalic',
    semiBoldItalic : 'Poppins-SemiBoldItalic',
    boldItalic : 'Poppins-BoldItalic',
    extraBoldItalic : 'Poppins-ExtraBoldItalic',
}